### ISSUE TITLE
메인 페이지가 오른쪽으로 밀리는 버그

### ISSUE THREAD

**Issue by AMATEURTOSS** [AMATEURTOSS/ft_transcendence#67]
```scss
body {
  padding-left:240px;
}
```
이거 때문인듯
